spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test1?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        aop-patterns:
            - com.main.demo.*
        filters: stat,wall
  thymeleaf:
    cache: false


#??mybatis
mybatis:
  type-aliases-package: com.liwei.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 9090
